services:
  host-app:
    build:
      context: ./sources
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./sources
        target: /usr/src/app
      - type: volume
        source: host-app-node_modules
        target: /usr/src/app/node_modules
    networks:
      - microfrontends
    command: ["npm", "run", "dev"]

volumes:
  host-app-node_modules:
    driver: local
    name: host-app-node_modules

networks:
  microfrontends:
    external: false